def menu_initial():
    print("\n")
    print(" \t\t\t\t\t\t=============MENU=============")
    print(" \t\t\t\t\t\t||                          ||")
    print(" \t\t\t\t\t\t==============================")
    print(" \t\t\t\t\t\t||                          ||")
    print(" \t\t\t\t\t\t||    [1] ----> Start       ||")
    print(" \t\t\t\t\t\t||                          ||")
    print(" \t\t\t\t\t\t==============================")
    print(" \t\t\t\t\t\t||                          ||")
    print(" \t\t\t\t\t\t||    [0] ----> Quit        ||")
    print(" \t\t\t\t\t\t||                          ||")
    print(" \t\t\t\t\t\t==============================")
    print("\n\n")

def game_mode():
    print("\n")
    print(" \t\t\t\t\t\t=================MENU==================")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t=======================================")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t||    [1] ----> Choose your game     ||")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t=======================================")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t||    [2] ----> Built-in game        ||")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t=======================================")
    print("\n\n")


def menu_difficulty():
    print("\n")
    print(" \t\t\t\t\t\t=================MENU==================")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t=======================================")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t||    [1] ----> Easy                 ||")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t=======================================")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t||    [2] ----> Medium               ||")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t=======================================")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t||    [3] ----> Hard                 ||")
    print(" \t\t\t\t\t\t||                                   ||")
    print(" \t\t\t\t\t\t=======================================")
    print("\n\n")
